export default function getAllProducts() {
  return [
    {
      id: 'CB-2-01-WM-001',
      slug: 'coated-blazer',
      name: "Coated Blazer", 
      category: "Woman", 
      categorySlug: 'woman', 
      price: 899_900, 
      stock: 30,
      imageUrl: '/assets/images/CoatedBlazer.jpg',
      description: `Fitted, single-breasted blazer in coated, woven fabric with peak lapels and one button at the front. Shoulder pads, jetted front pockets and a single back vent. Lined.`
    },
    {
      id: 'DBD-1-03-WM-003',
      slug: 'draped-bandeau-dress',
      name: "Draped Bandeau Dress",
      category: "Woman", 
      categorySlug: 'woman',
      price: 599_900,
      stock: 26,
      imageUrl: '/assets/images/DrapedBandeauDress.jpg',
      description: `Calf-length, fitted bandeau dress in jersey with a concealed silicone trim at the top and a concealed zip and hook-and-eye fastener at one side. Gathers at one side of the waist that create a gently draped effect. Straight-cut hem with a slit at one side. Lined bodice.`
    },
    {
      id: 'MS-5-09-WM-004',
      slug: 'mini-skirt', 
      name: 'Mini Skirt',  
      category: 'Woman',  
      categorySlug: 'woman',  
      price: 399_900,
      stock: 7,
      imageUrl: '/assets/images/MiniSkirt.jpg', 
      description: 'A cozy and stylish sweater, perfect for snowy days. Made with soft fabric to keep you warm and comfortable in cold weather.',
    },    
    {
      id: 'TLBT-2-06-WM-002',
      slug: 'tapared-linen-blend-trousers',
      name: 'Tapared Linen Blend Trousers', 
      category: "Woman", 
      categorySlug: 'woman', 
      price: 599_900,
      stock: 4,
      imageUrl: '/assets/images/TaperedLinenBlendTrousers.jpg',
      description: `Ankle-length trousers in a linen and viscose weave. High waist with a zip fly, an extended waistband with a concealed button and hook-and-eye fastening, and covered elastication at the back. Diagonal front pockets, fake welt pockets at the back and tapered legs with pleats at the top and creases at the front and back.`
    },
    {
      id: 'TFSJ-3-04-WM-005',
      slug: 'tie-front-sequined-jacket',
      name: 'Tie Front Sequined Jacket',
      category: 'Woman',
      categorySlug: 'woman',
      price: 1_500_000,
      stock: 0,
      imageUrl: '/assets/images/TieFrontSequinedJacket.jpg',
      description: `Short jacket in sequined velour with a round neckline, long sleeves and wide grosgrain ribbons that tie at the front. Jersey lining.`
    },
    {
        id: 'RFPC-5-09-M-006',
        slug: 'regular-fit-pima-cutton',  
        name: 'Reguler Fit Pima Cutton',  
        category: 'Man',  
        categorySlug: 'man',  
        price: 599_900,
        stock: 35,
        imageUrl: '/assets/images/RegularFitPimaCotton.jpg',  
        description: 'Short-sleeved shirt in a pima cotton weave with a resort collar, French front, yoke at the back and a straight-cut hem. Regular fit for comfortable wear and a classic silhouette.',    
    },
    {
      id: 'DRE-1-02-M-007',
      slug: 'slim-fit-waffled-polo-shirt',
      name: 'Slim Fit Waffled Polo Shirt',
      category: 'Man',
      categorySlug: 'man',
      price: 399_900, 
      stock: 27,
      imageUrl: '/assets/images/SlimFitWaffledPoloShirt.jpg',
      description: `Polo shirt in waffled jersey with a ribbed collar, button placket, short sleeves and a straight-cut hem with a small slit at each side. Slim fit that hugs the contours of your body, creating a fitted silhouette.`
    },
    {
      id: 'RFLBT-2-09-M-008',
      slug: 'classy-fit-dress',
      name: 'Regular Fit Linen Blend Trousers',
      category: "Man", 
      categorySlug: 'man',
      price: 599_900,
      stock: 30,
      imageUrl: '/assets/images/RegularFitLinenBlendTrousers.jpg',
      description: `Trousers in an airy cotton and linen weave. Regular fit with covered elastication and a drawstring at the waist, a zip fly with a concealed hook-and-eye fastener, pockets in the side seams and a welt pocket at the back. Cotton and linen blends combine the softness of cotton with the sturdiness of linen, creating a beautiful, textured fabric that is breathable and drapes perfectly.`
    },
    {
      id: 'LBV-2-06-M-009',
      slug: 'linen-blend-versatile-regular-fit-shirt',  
      name: 'Linen Blend Versatile Regular Fit Shirt',  
      category: "Man",  
      categorySlug: 'man',  
      price: 1_209_000,
      stock: 0,
      imageUrl: '/assets/images/LinenBlendVersatileRegularFitShirt.jpg', 
      description: "Short-sleeved utility shirt in an airy cotton and linen blend with a resort collar, French front and fitted shoulders at the back. Open chest pocket and straight hem. Loose fit for a wide but not oversized silhouette. A cotton and linen blend combines the softness of cotton with the toughness of linen, creating a beautifully textured fabric that absorbs sweat and drapes perfectly.",
    },
    {
      id: 'RFH-5-09-M-010',
      slug: 'regular-fit-hoodie',  
      name: 'Regular Fit Hoodie',  
      category: 'Man',  
      categorySlug: 'man',  
      price: 499_900,
      stock: 10,
      imageUrl: '/assets/images/RegularFitHoodie.jpg',  
      description: 'Long-sleeved hoodie in midweight sweatshirt fabric with a soft brushed inside. Kangaroo pocket, double-layered drawstring hood with a wrapover front, and ribbing at the cuffs and hem. Regular fit for comfortable wear and a classic silhouette.',
    },
    {
      id: '3PDS-5-09-BB-011',
      slug: '3-piece-dressy-set',  
      name: '3-Piece Dressy Set',  
      category: 'Baby',  
      categorySlug: 'baby',  
      price: 359_952,
      stock: 15,
      imageUrl: '/assets/images/3-piece dressy set.jpg',  
      description: 'Dressy set with a bodysuit in soft cotton jersey, a sweater vest in fine-knit cotton and a pair of joggers in sweatshirt fabric. Collared bodysuit with a bow tie, button placket, press-studs at the crotch and gathered seams around the legs for a more comfortable and snug fit around the nappy. V-neck sweater vest with a cable-knit front and ribbing around the neckline, armholes and hem. Joggers with an elasticated waist, cuffed hems and a soft brushed inside.',
    },
    {
      id: '2PBS-5-09-BB-012',
      slug: '2-piece-blouse-and-skirt-set',  
      name: '2-Piece Blouse and Skirt Set',  
      category: 'Baby',  
      categorySlug: 'baby',  
      price: 322_425,
      stock: 15,
      imageUrl: '/assets/images/2-piece blouse and skirt set.jpg',  
      description: '2-piece blouse and skirt setSet with a blouse in a cotton weave and a coordinating skirt in soft velvet with braces. Blouse with a broderie anglaise collar, wood-look buttons down the front and long sleeves with narrow elastication at the cuffs. Flared skirt with adjustable elastication at the waist for a comfortable fit around the tummy. Detachable braces with adjustable buttoning at the back.',
    },
    {
      id: '2PDV-5-09-BB-013',
      slug: '2-piece-dressy-velvet-set',  
      name: '2-Piece Dressy Velvet Set',  
      category: 'Baby',  
      categorySlug: 'baby',  
      price: 449_925,
      stock: 12,
      imageUrl: '/assets/images/2-piece dressy velvet set.jpg',  
      description: 'Dressy set with a waistcoat and a pair of matching trousers in soft velvet. Taffeta-lined waistcoat with buttons down the front. Trousers with adjustable elastication at the waist for a comfortable fit around the tummy, a fake fly and button and fake side pockets.',
    },
    {
      id: 'CSC-5-09-BB-014',
      slug: 'collareds-weatshirt-cardigan',  
      name: 'Collared Sweatshirt Cardigan',  
      category: 'Baby',  
      categorySlug: 'baby',  
      price: 224_925,
      stock: 10,
      imageUrl: '/assets/images/Collared sweatshirt cardigan.jpg',  
      description: 'Straight-cut cardigan in sweatshirt fabric with a rounded, frill-trimmed collar in woven fabric. Press-studs down the front and patch pockets on the front. Soft brushed inside.',
    },
    {
      id: 'DS-5-09-BB-015',
      slug: 'dressy-set',  
      name: 'Dressy Set',  
      category: 'Baby',  
      categorySlug: 'baby',  
      price: 300_000,
      stock: 12,
      imageUrl: '/assets/images/Dressy set.jpg',  
      description: 'Set with a shirt and pair of lined trousers in a cotton weave with matching braces. Shirt with a button-down collar, buttons down the front, a yoke at the back, long sleeves with buttoned cuffs, and a rounded hem. Trousers with an adjustable, elasticated waist, fake fly with a button, patch front pockets and a fake back pocket. Soft jersey lining. Detachable elastic braces with imitation leather details.',
    },
    {
      id: 'FTD-5-09-BB-016',
      slug: 'flounce-trimmed-dress',  
      name: 'Flounce Trimmed Dress',  
      category: 'Baby',  
      categorySlug: 'baby',  
      price: 224_925,
      stock: 5,
      imageUrl: '/assets/images/Flounce-trimmed dress.jpg',  
      description: 'Sleeveless dress with flounces at the front that continue over the shoulders and down the back. Round neckline, buttons at the back and a gathered seam at the waist. Lined.',
    },
    {
      id: 'PS-5-09-BB-017',
      slug: '4-piece-set',  
      name: '4-Piece Set',  
      category: 'Baby',  
      categorySlug: 'baby',  
      price: 449_925,
      stock: 7,
      imageUrl: '/assets/images/4-Potong set.jpg',  
      description: 'The set consists of a shirt in woven cotton with a bow tie, a vest and shorts in linen and woven cotton. Lined vest with buttons on the front. Knee-length shorts with an adjustable elasticated waist, faux zipper and buttons, and faux diagonal side pockets. Shirt with shirt collar, row of buttons down the front, short sleeves with reverse stitching, and rounded hem. Bow tie with adjustable elastic strap and plastic buckle at the back.',
    },
    {
      id: 'FG-5-09-BB-018',
      slug: 'fluffy-gilet',  
      name: 'Fluffy Gilet',  
      category: 'Baby',  
      categorySlug: 'baby',  
      price: 187_425,
      stock: 2,
      imageUrl: '/assets/images/Fluffy gilet.jpg',  
      description: 'Gilet in soft, fluffy fabric with a button at the top. Cotton lining.',
    },
    {
      id: 'STD-5-09-CH-019',
      slug: 'sequined-tulle-dress',  
      name: 'Sequined Tulle Dress',  
      category: 'Children',  
      categorySlug: 'children',  
      price: 449_925,
      stock: 5,
      imageUrl: '/assets/images/Sequined tulle dress.jpg',  
      description: 'Sleeveless dress with a sequined jersey bodice and lined skirt with several tulle tiers creating volume and movement. Shimmering buttons at the back.',
    },
    {
      id: '2PS-5-09-CH-020',
      slug: '2-piece-set',  
      name: '2-Piece Set',  
      category: 'Children',  
      categorySlug: 'children',  
      price: 262_425,
      stock: 0,
      imageUrl: '/assets/images/2-piece set.jpg',  
      description: 'Set with a top and skirt. Top with a round neckline and short, voluminous puff sleeves with concealed elastication at the cuffs. Skirt with covered elastication at the waist. Unlined.',
    },
    {
      id: 'VS-5-09-CH-021',
      slug: 'voluminous-skirt',  
      name: 'Voluminous Skirt',  
      category: 'Children',  
      categorySlug: 'children',  
      price: 262_425,
      stock: 3,
      imageUrl: '/assets/images/Voluminous skirt.jpg',  
      description: 'Tiered, voluminous skirt in woven fabric with covered elastication at the back of the waist. Lined.',
    },
    {
      id: 'ZTH-5-09-SP-022',
      slug: 'zip-through-hoodie',  
      name: 'Zip Through Hoodie',  
      category: 'Sport',  
      categorySlug: 'sport',  
      price: 699_900,
      stock: 50,
      imageUrl: '/assets/images/Zip-through hoodie.jpg',  
      description: 'Zip-through hoodie in sweatshirt fabric with a soft brushed inside. Regular fit with a hood, zip down the front and welt front pockets. Dropped shoulders and wide, long sleeves and ribbing at the cuffs and hem.',
    },
    {
      id: 'DMS-5-09-SP-023',
      slug: 'dry-move-seamless-sports-bra',  
      name: 'Dry Move Seamless Sports Bra',  
      category: 'Sport',  
      categorySlug: 'sport',  
      price: 199_900,
      stock: 3,
      imageUrl: '/assets/images/DryMoveSeamlessSportsBra.jpg',  
      description: 'Ribbed sports bra in DryMove™ functional fabric that helps to wick away moisture from your skin, keeping you comfortably dry while you move. Wide shoulder straps, lined cups with removable inserts that shape the bust, and a racer back. Medium support suitable for moderate-intensity workouts. The bra is designed with the minimum number of seams for a more comfortable fit and increased mobility.',
    },
    {
      id: 'SMSL-5-09-SP-024',
      slug: 'soft-move-sports-leggings',  
      name: 'Soft Move Sports Leggings',  
      category: 'Sport',  
      categorySlug: 'sport',  
      price: 599_900,
      stock: 50,
      imageUrl: '/assets/images/SoftMoveSports leggings.jpg',  
      description: 'Sports leggings in DryMove functional fabric that helps to wick away moisture from your skin and SoftMove™, a supersoft, functional fabric that is lightweight and provides extra freedom of movement. High waist with a wide waist panel.',
    },
    {
      id: 'DMSS-5-09-SP-025',
      slug: 'dry-Move-2-in-1-sports-shorts',  
      name: 'Dry Move 2-in-1 Sports Shortss',  
      category: 'Sport',  
      categorySlug: 'sport',  
      price: 599_900,
      stock: 50,
      imageUrl: '/assets/images/DryMove2-in-1SportsShorts.jpg',  
      description: 'Regular-fit sports shorts in DryMove™ functional fabric that helps to wick away moisture from your skin, keeping you comfortably dry while you move. Elasticated waistband with a concealed drawstring, diagonal side pockets and a small slit at the hems. Four-way stretch for maximum comfort and added mobility. The shorts are layered over jersey cycling shorts.',
    },
  ];
}


